### ISSUE TITLE
请问，小爱的keyid,secret如何获取？git中链接不能用了

### ISSUE THREAD

**Issue by zhangzhenfeng** [zhusaidong/XiaoAi#2]
请问，小爱的keyid,secret如何获取？

**Comment by zhusaidong** [comment]
小爱的开放平台升级了，原来的地址不能用来。
新地址：https://developers.xiaoai.mi.com/skills/create/list
点击进入某个技能，可以看到
![image](https://user-images.githubusercontent.com/3039961/129529977-04fe800a-4fdb-49c4-b165-f40f8f89a1d7.png)
